version: '3'

services:
  server:
    container_name: l10n.server
    image: azraeht/serge-zing:latest
    ports: 
      - 8000:8000
    environment:
      - SERGE_DATA_DIR=/data
      - ZING_DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - GIT_SERVER_DOMAIN=gitlab.priv.sewan.fr
      - SERGE_SETTINGS=/etc/serge-zing/serge.conf
      - ZING_SETTINGS=/etc/serge-zing/zing.conf
    volumes:
      - ./config:/etc/serge-zing # Serge configuration
      - ./data:/data # Persistance for serge data (files and db)
      - ~/.ssh_no_secured:/tmp/.ssh:ro # SSH key mount for non public repo
    depends_on:
      - db
      - redis
    networks: 
      - default

  db:
    container_name: l10n.db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks: 
      - default

  redis:
    container_name: l10n.redis
    image: redis:latest
    networks: 
      - default
    
networks:
  default:
    driver: bridge
