version: '3'

services:
  serge:
    container_name: serge.server
    network_mode: "bridge"
    #build: ./serge
    image: azraeht/serge:1.3-xenial
    environment:
      - SERGE_DATA_DIR=/data
      # - GIT_SERVER_DOMAIN=git.example.com
    volumes:
      - ./conf:/etc/serge # Serge configuration
      - ./data:/data # Persistance for serge data (files and db)
      # ~/.ssh/:/tmp/.ssh:ro # SSH key mount for non public repo

  zing:
    container_name: zing.server
    network_mode: "bridge"
    build: ./zing
    #image: azraeht/zing:0.8.8
    environment:
      - ZING_DB_ROOT_PASSWORD=rk7b5v7Q4SSRbTSr
    volumes:
      - .data:/data
    depends_on:
      - db
      - redis

  db:
    container_name: zing.database
    network_mode: "bridge"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rk7b5v7Q4SSRbTSr
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    container_name: zing.redis
    network_mode: "bridge"
    image: redis:latest
