version: '3'

services:
  serge:
    container_name: serge.server
    network_mode: "bridge"
    #build: ./serge
    image: azraeht/serge:1.3-xenial
    environnement:
      - SERGE_DATA_DIR=/data
    volumes:
      - ./conf:/etc/serge
      - ./data:/data

  zing:
    container_name: zing.server
    network_mode: "bridge"
    build: ./zing
    #image: azraeht/zing:XX.XX-xenial
    volumes:
      - .data:/data
